# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=80)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(null=True, blank=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(unique=True, max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Balancesheetnonfin',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('symbolnumber', models.CharField(max_length=20, null=True, db_column='SymbolNumber', blank=True)),
                ('year', models.CharField(max_length=5, null=True, db_column='Year', blank=True)),
                ('quarter', models.CharField(max_length=2, null=True, db_column='Quarter', blank=True)),
                ('c1', models.FloatField(null=True, db_column='C1', blank=True)),
                ('c2', models.FloatField(null=True, db_column='C2', blank=True)),
                ('c3', models.FloatField(null=True, db_column='C3', blank=True)),
                ('c4', models.FloatField(null=True, db_column='C4', blank=True)),
                ('c5', models.FloatField(null=True, db_column='C5', blank=True)),
                ('c6', models.FloatField(null=True, db_column='C6', blank=True)),
                ('c7', models.FloatField(null=True, db_column='C7', blank=True)),
                ('c8', models.FloatField(null=True, db_column='C8', blank=True)),
                ('c9', models.FloatField(null=True, db_column='C9', blank=True)),
                ('c10', models.FloatField(null=True, db_column='C10', blank=True)),
                ('c11', models.FloatField(null=True, db_column='C11', blank=True)),
                ('c12', models.FloatField(null=True, db_column='C12', blank=True)),
                ('c13', models.FloatField(null=True, db_column='C13', blank=True)),
                ('c14', models.FloatField(null=True, db_column='C14', blank=True)),
                ('c15', models.FloatField(null=True, db_column='C15', blank=True)),
                ('c16', models.FloatField(null=True, db_column='C16', blank=True)),
                ('c17', models.FloatField(null=True, db_column='C17', blank=True)),
                ('c18', models.FloatField(null=True, db_column='C18', blank=True)),
                ('c19', models.FloatField(null=True, db_column='C19', blank=True)),
                ('c20', models.FloatField(null=True, db_column='C20', blank=True)),
                ('c21', models.FloatField(null=True, db_column='C21', blank=True)),
                ('c22', models.FloatField(null=True, db_column='C22', blank=True)),
                ('c23', models.FloatField(null=True, db_column='C23', blank=True)),
                ('c24', models.FloatField(null=True, db_column='C24', blank=True)),
                ('c25', models.FloatField(null=True, db_column='C25', blank=True)),
                ('c26', models.FloatField(null=True, db_column='C26', blank=True)),
                ('c27', models.FloatField(null=True, db_column='C27', blank=True)),
                ('c28', models.FloatField(null=True, db_column='C28', blank=True)),
                ('c29', models.FloatField(null=True, db_column='C29', blank=True)),
                ('c30', models.FloatField(null=True, db_column='C30', blank=True)),
                ('c31', models.FloatField(null=True, db_column='C31', blank=True)),
                ('c32', models.FloatField(null=True, db_column='C32', blank=True)),
                ('c33', models.FloatField(null=True, db_column='C33', blank=True)),
                ('c34', models.FloatField(null=True, db_column='C34', blank=True)),
                ('c35', models.FloatField(null=True, db_column='C35', blank=True)),
                ('c36', models.FloatField(null=True, db_column='C36', blank=True)),
                ('c37', models.FloatField(null=True, db_column='C37', blank=True)),
                ('c38', models.FloatField(null=True, db_column='C38', blank=True)),
                ('c39', models.FloatField(null=True, db_column='C39', blank=True)),
                ('c40', models.FloatField(null=True, db_column='C40', blank=True)),
                ('c41', models.FloatField(null=True, db_column='C41', blank=True)),
                ('c42', models.FloatField(null=True, db_column='C42', blank=True)),
                ('c43', models.FloatField(null=True, db_column='C43', blank=True)),
                ('c44', models.FloatField(null=True, db_column='C44', blank=True)),
                ('c45', models.FloatField(null=True, db_column='C45', blank=True)),
                ('c46', models.FloatField(null=True, db_column='C46', blank=True)),
                ('c47', models.FloatField(null=True, db_column='C47', blank=True)),
                ('c48', models.FloatField(null=True, db_column='C48', blank=True)),
                ('c49', models.FloatField(null=True, db_column='C49', blank=True)),
                ('c50', models.FloatField(null=True, db_column='C50', blank=True)),
                ('c51', models.FloatField(null=True, db_column='C51', blank=True)),
                ('c52', models.FloatField(null=True, db_column='C52', blank=True)),
                ('c53', models.FloatField(null=True, db_column='C53', blank=True)),
                ('c54', models.FloatField(null=True, db_column='C54', blank=True)),
                ('c55', models.FloatField(null=True, db_column='C55', blank=True)),
                ('c56', models.FloatField(null=True, db_column='C56', blank=True)),
                ('c57', models.FloatField(null=True, db_column='C57', blank=True)),
                ('c58', models.FloatField(null=True, db_column='C58', blank=True)),
                ('c59', models.FloatField(null=True, db_column='C59', blank=True)),
                ('c60', models.FloatField(null=True, db_column='C60', blank=True)),
                ('c61', models.FloatField(null=True, db_column='C61', blank=True)),
                ('c62', models.FloatField(null=True, db_column='C62', blank=True)),
                ('c63', models.FloatField(null=True, db_column='C63', blank=True)),
                ('c64', models.FloatField(null=True, db_column='C64', blank=True)),
                ('c65', models.FloatField(null=True, db_column='C65', blank=True)),
                ('c66', models.FloatField(null=True, db_column='C66', blank=True)),
                ('c67', models.FloatField(null=True, db_column='C67', blank=True)),
            ],
            options={
                'db_table': 'BalanceSheetNonFin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cashflownonfin',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('symbolnumber', models.CharField(max_length=20, null=True, db_column='SymbolNumber', blank=True)),
                ('year', models.CharField(max_length=5, null=True, db_column='Year', blank=True)),
                ('quarter', models.CharField(max_length=2, null=True, db_column='Quarter', blank=True)),
                ('c1', models.FloatField(null=True, db_column='C1', blank=True)),
                ('c2', models.FloatField(null=True, db_column='C2', blank=True)),
                ('c3', models.FloatField(null=True, db_column='C3', blank=True)),
                ('c4', models.FloatField(null=True, db_column='C4', blank=True)),
                ('c5', models.FloatField(null=True, db_column='C5', blank=True)),
                ('c6', models.FloatField(null=True, db_column='C6', blank=True)),
                ('c7', models.FloatField(null=True, db_column='C7', blank=True)),
                ('c8', models.FloatField(null=True, db_column='C8', blank=True)),
                ('c9', models.FloatField(null=True, db_column='C9', blank=True)),
                ('c10', models.FloatField(null=True, db_column='C10', blank=True)),
                ('c11', models.FloatField(null=True, db_column='C11', blank=True)),
                ('c12', models.FloatField(null=True, db_column='C12', blank=True)),
                ('c13', models.FloatField(null=True, db_column='C13', blank=True)),
                ('c14', models.FloatField(null=True, db_column='C14', blank=True)),
                ('c15', models.FloatField(null=True, db_column='C15', blank=True)),
                ('c16', models.FloatField(null=True, db_column='C16', blank=True)),
                ('c17', models.FloatField(null=True, db_column='C17', blank=True)),
                ('c18', models.FloatField(null=True, db_column='C18', blank=True)),
                ('c19', models.FloatField(null=True, db_column='C19', blank=True)),
                ('c20', models.FloatField(null=True, db_column='C20', blank=True)),
                ('c21', models.FloatField(null=True, db_column='C21', blank=True)),
                ('c22', models.FloatField(null=True, db_column='C22', blank=True)),
                ('c23', models.FloatField(null=True, db_column='C23', blank=True)),
                ('c24', models.FloatField(null=True, db_column='C24', blank=True)),
                ('c25', models.FloatField(null=True, db_column='C25', blank=True)),
                ('c26', models.FloatField(null=True, db_column='C26', blank=True)),
                ('c27', models.FloatField(null=True, db_column='C27', blank=True)),
                ('c28', models.FloatField(null=True, db_column='C28', blank=True)),
                ('c29', models.FloatField(null=True, db_column='C29', blank=True)),
                ('c30', models.FloatField(null=True, db_column='C30', blank=True)),
                ('c31', models.FloatField(null=True, db_column='C31', blank=True)),
                ('c32', models.FloatField(null=True, db_column='C32', blank=True)),
                ('c33', models.FloatField(null=True, db_column='C33', blank=True)),
                ('c34', models.FloatField(null=True, db_column='C34', blank=True)),
                ('c35', models.FloatField(null=True, db_column='C35', blank=True)),
                ('c36', models.FloatField(null=True, db_column='C36', blank=True)),
                ('c37', models.FloatField(null=True, db_column='C37', blank=True)),
                ('c38', models.FloatField(null=True, db_column='C38', blank=True)),
                ('c39', models.FloatField(null=True, db_column='C39', blank=True)),
                ('c40', models.FloatField(null=True, db_column='C40', blank=True)),
                ('c41', models.FloatField(null=True, db_column='C41', blank=True)),
                ('c42', models.FloatField(null=True, db_column='C42', blank=True)),
                ('c43', models.FloatField(null=True, db_column='C43', blank=True)),
                ('c44', models.FloatField(null=True, db_column='C44', blank=True)),
                ('c45', models.FloatField(null=True, db_column='C45', blank=True)),
                ('c46', models.FloatField(null=True, db_column='C46', blank=True)),
                ('c47', models.FloatField(null=True, db_column='C47', blank=True)),
                ('c48', models.FloatField(null=True, db_column='C48', blank=True)),
                ('c49', models.FloatField(null=True, db_column='C49', blank=True)),
                ('c50', models.FloatField(null=True, db_column='C50', blank=True)),
                ('c51', models.FloatField(null=True, db_column='C51', blank=True)),
                ('c52', models.FloatField(null=True, db_column='C52', blank=True)),
                ('c53', models.FloatField(null=True, db_column='C53', blank=True)),
                ('c54', models.FloatField(null=True, db_column='C54', blank=True)),
                ('c55', models.FloatField(null=True, db_column='C55', blank=True)),
                ('c56', models.FloatField(null=True, db_column='C56', blank=True)),
                ('c57', models.FloatField(null=True, db_column='C57', blank=True)),
                ('c58', models.FloatField(null=True, db_column='C58', blank=True)),
                ('c59', models.FloatField(null=True, db_column='C59', blank=True)),
            ],
            options={
                'db_table': 'CashFlowNonFin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('symbolnumber', models.CharField(max_length=20, null=True, db_column='SymbolNumber', blank=True)),
                ('circulationstock', models.FloatField(null=True, db_column='CirculationStock', blank=True)),
                ('year', models.CharField(max_length=5, null=True, db_column='Year', blank=True)),
                ('quarter', models.CharField(max_length=2, null=True, db_column='Quarter', blank=True)),
                ('incometax', models.FloatField(null=True, db_column='IncomeTax', blank=True)),
                ('netprofit', models.FloatField(null=True, db_column='NetProfit', blank=True)),
                ('accountsreceivable', models.FloatField(null=True, db_column='AccountsReceivable', blank=True)),
                ('advancepayment', models.FloatField(null=True, db_column='AdvancePayment', blank=True)),
                ('stock', models.FloatField(null=True, db_column='Stock', blank=True)),
                ('totalcurrentassets', models.FloatField(null=True, db_column='TotalCurrentAssets', blank=True)),
                ('fixedassets', models.FloatField(null=True, db_column='FixedAssets', blank=True)),
                ('intangibleassets', models.FloatField(null=True, db_column='IntangibleAssets', blank=True)),
                ('goodwill', models.FloatField(null=True, db_column='GoodWill', blank=True)),
                ('totalcapital', models.FloatField(null=True, db_column='TotalCapital', blank=True)),
                ('payableaccount', models.FloatField(null=True, db_column='PayableAccount', blank=True)),
                ('payableinterest', models.FloatField(null=True, db_column='PayableInterest', blank=True)),
                ('othercurrentliability', models.FloatField(null=True, db_column='OtherCurrentLiability', blank=True)),
                ('totalcurrentliability', models.FloatField(null=True, db_column='TotalCurrentLiability', blank=True)),
                ('longtermloan', models.FloatField(null=True, db_column='LongtermLoan', blank=True)),
                ('longtermpayable', models.FloatField(null=True, db_column='LongtermPayable', blank=True)),
                ('totalnoncurrentliability', models.FloatField(null=True, db_column='TotalNonCurrentLiability', blank=True)),
                ('totalliability', models.FloatField(null=True, db_column='TotalLiability', blank=True)),
                ('assetvalue', models.FloatField(null=True, db_column='AssetValue', blank=True)),
                ('cashpayment', models.FloatField(null=True, db_column='CashPayment', blank=True)),
                ('cashforinterest', models.FloatField(null=True, db_column='CashForInterest', blank=True)),
                ('depreciation', models.FloatField(null=True, db_column='Depreciation', blank=True)),
                ('amortization', models.FloatField(null=True, db_column='Amortization', blank=True)),
                ('longtermamortization', models.FloatField(null=True, db_column='LongtermAmortization', blank=True)),
                ('quickratio', models.FloatField(null=True, db_column='QuickRatio', blank=True)),
                ('totalcapitalratioofreturn', models.FloatField(null=True, db_column='TotalCapitalRatioOfReturn', blank=True)),
                ('assetratioofreturn', models.FloatField(null=True, db_column='AssetRatioOfReturn', blank=True)),
                ('volatility', models.FloatField(null=True, db_column='Volatility', blank=True)),
                ('netfixedassetsrate', models.FloatField(null=True, db_column='NetFixedAssetsRate', blank=True)),
                ('cnname', models.CharField(max_length=50, null=True, db_column='CNName', blank=True)),
                ('identification', models.CharField(max_length=20, serialize=False, primary_key=True, db_column='Identification')),
            ],
            options={
                'db_table': 'Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(null=True, blank=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, serialize=False, primary_key=True)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finrationonfin',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('symbolnumber', models.CharField(max_length=20, null=True, db_column='SymbolNumber', blank=True)),
                ('year', models.CharField(max_length=5, null=True, db_column='Year', blank=True)),
                ('quarter', models.CharField(max_length=2, null=True, db_column='Quarter', blank=True)),
                ('c1', models.FloatField(null=True, db_column='C1', blank=True)),
                ('c2', models.FloatField(null=True, db_column='C2', blank=True)),
                ('c3', models.FloatField(null=True, db_column='C3', blank=True)),
                ('c4', models.FloatField(null=True, db_column='C4', blank=True)),
                ('c5', models.FloatField(null=True, db_column='C5', blank=True)),
                ('c6', models.FloatField(null=True, db_column='C6', blank=True)),
                ('c7', models.FloatField(null=True, db_column='C7', blank=True)),
                ('c8', models.FloatField(null=True, db_column='C8', blank=True)),
                ('c9', models.FloatField(null=True, db_column='C9', blank=True)),
                ('c10', models.FloatField(null=True, db_column='C10', blank=True)),
                ('c11', models.FloatField(null=True, db_column='C11', blank=True)),
                ('c12', models.FloatField(null=True, db_column='C12', blank=True)),
                ('c13', models.FloatField(null=True, db_column='C13', blank=True)),
                ('c14', models.FloatField(null=True, db_column='C14', blank=True)),
                ('c15', models.FloatField(null=True, db_column='C15', blank=True)),
                ('c16', models.FloatField(null=True, db_column='C16', blank=True)),
                ('c17', models.FloatField(null=True, db_column='C17', blank=True)),
                ('c18', models.FloatField(null=True, db_column='C18', blank=True)),
                ('c19', models.FloatField(null=True, db_column='C19', blank=True)),
                ('c20', models.FloatField(null=True, db_column='C20', blank=True)),
                ('c21', models.FloatField(null=True, db_column='C21', blank=True)),
                ('c22', models.FloatField(null=True, db_column='C22', blank=True)),
                ('c23', models.FloatField(null=True, db_column='C23', blank=True)),
                ('c24', models.FloatField(null=True, db_column='C24', blank=True)),
                ('c25', models.FloatField(null=True, db_column='C25', blank=True)),
                ('c26', models.FloatField(null=True, db_column='C26', blank=True)),
                ('c27', models.FloatField(null=True, db_column='C27', blank=True)),
                ('c28', models.FloatField(null=True, db_column='C28', blank=True)),
                ('c29', models.FloatField(null=True, db_column='C29', blank=True)),
                ('c30', models.FloatField(null=True, db_column='C30', blank=True)),
                ('c31', models.FloatField(null=True, db_column='C31', blank=True)),
                ('c32', models.FloatField(null=True, db_column='C32', blank=True)),
                ('c33', models.FloatField(null=True, db_column='C33', blank=True)),
                ('c34', models.FloatField(null=True, db_column='C34', blank=True)),
                ('c35', models.FloatField(null=True, db_column='C35', blank=True)),
                ('c36', models.FloatField(null=True, db_column='C36', blank=True)),
                ('c37', models.FloatField(null=True, db_column='C37', blank=True)),
                ('c38', models.FloatField(null=True, db_column='C38', blank=True)),
                ('c39', models.FloatField(null=True, db_column='C39', blank=True)),
                ('c40', models.FloatField(null=True, db_column='C40', blank=True)),
                ('c41', models.FloatField(null=True, db_column='C41', blank=True)),
                ('c42', models.FloatField(null=True, db_column='C42', blank=True)),
                ('c43', models.FloatField(null=True, db_column='C43', blank=True)),
                ('c44', models.FloatField(null=True, db_column='C44', blank=True)),
                ('c45', models.FloatField(null=True, db_column='C45', blank=True)),
                ('c46', models.FloatField(null=True, db_column='C46', blank=True)),
                ('c47', models.FloatField(null=True, db_column='C47', blank=True)),
                ('c48', models.FloatField(null=True, db_column='C48', blank=True)),
                ('c49', models.FloatField(null=True, db_column='C49', blank=True)),
                ('c50', models.FloatField(null=True, db_column='C50', blank=True)),
                ('c51', models.FloatField(null=True, db_column='C51', blank=True)),
                ('c52', models.FloatField(null=True, db_column='C52', blank=True)),
                ('c53', models.FloatField(null=True, db_column='C53', blank=True)),
                ('c54', models.FloatField(null=True, db_column='C54', blank=True)),
                ('c55', models.FloatField(null=True, db_column='C55', blank=True)),
                ('c56', models.FloatField(null=True, db_column='C56', blank=True)),
                ('c57', models.FloatField(null=True, db_column='C57', blank=True)),
                ('c58', models.FloatField(null=True, db_column='C58', blank=True)),
                ('c59', models.FloatField(null=True, db_column='C59', blank=True)),
                ('c60', models.FloatField(null=True, db_column='C60', blank=True)),
                ('c61', models.FloatField(null=True, db_column='C61', blank=True)),
                ('c62', models.FloatField(null=True, db_column='C62', blank=True)),
                ('c63', models.FloatField(null=True, db_column='C63', blank=True)),
                ('c64', models.FloatField(null=True, db_column='C64', blank=True)),
                ('c65', models.FloatField(null=True, db_column='C65', blank=True)),
                ('c66', models.FloatField(null=True, db_column='C66', blank=True)),
                ('c67', models.FloatField(null=True, db_column='C67', blank=True)),
                ('c68', models.FloatField(null=True, db_column='C68', blank=True)),
                ('c69', models.FloatField(null=True, db_column='C69', blank=True)),
                ('c70', models.FloatField(null=True, db_column='C70', blank=True)),
                ('c71', models.FloatField(null=True, db_column='C71', blank=True)),
                ('c72', models.FloatField(null=True, db_column='C72', blank=True)),
                ('c73', models.FloatField(null=True, db_column='C73', blank=True)),
                ('c74', models.FloatField(null=True, db_column='C74', blank=True)),
            ],
            options={
                'db_table': 'FinRatioNonFin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guben',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('symbolnumber', models.CharField(max_length=20, null=True, db_column='SymbolNumber', blank=True)),
                ('date', models.CharField(max_length=50, null=True, db_column='Date', blank=True)),
                ('circulationstock', models.FloatField(null=True, db_column='CirculationStock', blank=True)),
                ('totalstock', models.FloatField(null=True, db_column='TotalStock', blank=True)),
                ('changereason', models.CharField(max_length=50, null=True, db_column='ChangeReason', blank=True)),
                ('circulationa', models.FloatField(null=True, db_column='CirculationA', blank=True)),
                ('circulationb', models.FloatField(null=True, db_column='CirculationB', blank=True)),
                ('circulationh', models.FloatField(null=True, db_column='CirculationH', blank=True)),
                ('year', models.CharField(max_length=5, null=True, blank=True)),
                ('quarter', models.CharField(max_length=2, null=True, db_column='Quarter', blank=True)),
            ],
            options={
                'db_table': 'guben',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('symbolnumber', models.CharField(max_length=20, null=True, db_column='SymbolNumber', blank=True)),
                ('cnname', models.CharField(max_length=50, null=True, db_column='CNName', blank=True)),
                ('enname', models.CharField(max_length=50, null=True, db_column='ENName', blank=True)),
            ],
            options={
                'db_table': 'list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profitnonfin',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('symbolnumber', models.CharField(max_length=20, null=True, db_column='SymbolNumber', blank=True)),
                ('year', models.CharField(max_length=5, null=True, db_column='Year', blank=True)),
                ('quarter', models.CharField(max_length=2, null=True, db_column='Quarter', blank=True)),
                ('c1', models.FloatField(null=True, db_column='C1', blank=True)),
                ('c2', models.FloatField(null=True, db_column='C2', blank=True)),
                ('c3', models.FloatField(null=True, db_column='C3', blank=True)),
                ('c4', models.FloatField(null=True, db_column='C4', blank=True)),
                ('c5', models.FloatField(null=True, db_column='C5', blank=True)),
                ('c6', models.FloatField(null=True, db_column='C6', blank=True)),
                ('c7', models.FloatField(null=True, db_column='C7', blank=True)),
                ('c8', models.FloatField(null=True, db_column='C8', blank=True)),
                ('c9', models.FloatField(null=True, db_column='C9', blank=True)),
                ('c10', models.FloatField(null=True, db_column='C10', blank=True)),
                ('c11', models.FloatField(null=True, db_column='C11', blank=True)),
                ('c12', models.FloatField(null=True, db_column='C12', blank=True)),
                ('c13', models.FloatField(null=True, db_column='C13', blank=True)),
                ('c14', models.FloatField(null=True, db_column='C14', blank=True)),
                ('c15', models.FloatField(null=True, db_column='C15', blank=True)),
                ('c16', models.FloatField(null=True, db_column='C16', blank=True)),
                ('c17', models.FloatField(null=True, db_column='C17', blank=True)),
                ('c18', models.FloatField(null=True, db_column='C18', blank=True)),
                ('c19', models.FloatField(null=True, db_column='C19', blank=True)),
                ('c20', models.FloatField(null=True, db_column='C20', blank=True)),
                ('c21', models.FloatField(null=True, db_column='C21', blank=True)),
                ('c22', models.FloatField(null=True, db_column='C22', blank=True)),
                ('c23', models.FloatField(null=True, db_column='C23', blank=True)),
                ('c24', models.FloatField(null=True, db_column='C24', blank=True)),
                ('c25', models.FloatField(null=True, db_column='C25', blank=True)),
                ('c26', models.FloatField(null=True, db_column='C26', blank=True)),
                ('c27', models.FloatField(null=True, db_column='C27', blank=True)),
            ],
            options={
                'db_table': 'ProfitNonFin',
                'managed': False,
            },
        ),
    ]
